- include: spine_setup.yml

- set_fact:
    bridges: "{{ interfaces[ansible_hostname].bridges }}"
  when: interfaces[ansible_hostname].bridges is defined

- set_fact:
    peerlink: "{{ interfaces[ansible_hostname].peerlink }}"
  when: interfaces[ansible_hostname].peerlink is defined

- set_fact:
    peerlink: "{{ interfaces[ansible_hostname].peerlink }}"
  when: interfaces[ansible_hostname].peerlink is defined

- set_fact:
    bond1: "{{ interfaces[ansible_hostname].bond1 }}"
  when: interfaces[ansible_hostname].bond1 is defined

- set_fact:
    bond2: "{{ interfaces[ansible_hostname].bond2 }}"
  when: interfaces[ansible_hostname].bond2 is defined

- set_fact:
    bond3: "{{ interfaces[ansible_hostname].bond3 }}"
  when: interfaces[ansible_hostname].bond3 is defined

- set_fact:
    svi: "{{ addresses[ansible_hostname].svi }}"
  when: addresses[ansible_hostname].svi is defined

- name: configure bond1
  nclu:
    commands:
      - add bond "{{ item.name }}" slaves "{{ item.members }}"
      - add bond "{{ item.name }}" clag id "{{ item.clag_id }}"
    atomic: true
  with_items: "{{ bond1 }}"
  when: bond1 is defined

- name: configure bond2
  nclu:
    commands:
      - add bond "{{ item.name }}" slaves "{{ item.members }}"
      - add bond "{{ item.name }}" clag id "{{ item.clag_id }}"
    atomic: true
  with_items: "{{ bond2 }}"
  when: bond2 is defined

- name: configure bond3
  nclu:
    commands:
      - add bond "{{ item.name }}" slaves "{{ item.members }}"
      - add bond "{{ item.name }}" clag id "{{ item.clag_id }}"
    atomic: true
  with_items: "{{ bond3 }}"
  when: bond3 is defined

- name: configure vlan 10 vrr
  nclu:
    commands:
      - add interface ip address "{{ item }}"
      - add interface ip address-virtual "{{ vrr[ansible_hostname].vmac }}"
      - add interface ip gateway "{{ vrr[ansible_hostname].vip }}"
    atomic: true
  with_items: "{{ svi }}"
  when: vrr[ansible_hostname] is defined

- name: Add source /etc/network/interfaces.d/*
  lineinfile: dest=/etc/network/interfaces state=present line='source /etc/network/interfaces.d/*' insertbefore=BOF
  become: yes

- name: Restart networking
  service: name=networking state=restarted
  become: yes

- name: Restart clagd
  service: name=clagd state=restarted
  become: yes
