- set_fact:
    bridges: "{{ interfaces[ansible_hostname].bridges }}"
  when: interfaces[ansible_hostname].bridges is defined

- set_fact:
    peerlink: "{{ interfaces[ansible_hostname].peerlink }}"
  when: interfaces[ansible_hostname].peerlink is defined

- set_fact:
    host_clag: "{{ interfaces[ansible_hostname].host_clag }}"
  when: interfaces[ansible_hostname].host_clag is defined

- set_fact:
    svi: "{{ addresses[ansible_hostname].svi }}"
  when: addresses[ansible_hostname].svi is defined

- name: configure loopback interface
  nclu:
    command:
      - add loopback lo ip address '{{ loopback_ip }}/32'
    atomic: true
  when: loopback_ip is defined

- name: configure bridges
  nclu:
    command:
       - add bridge bridge ports "{{ item.members }}"
       - add bridge bridge vids 1-100
    commit: true
  with_items: "{{ bridges }}"
  when: bridges is defined

#- name: configure bridges
#  cl_bridge:
#    name: "{{ item.name }}"
#    vlan_aware: yes
#    ports: "{{ item.members }}"
#    stp: true
#    vids: "1-100"
#    pvid: "1"
#  with_items: "{{ bridges }}"
#  when: bridges is defined

- name: configure peerlink
  nclu:
    commands: add bond "{{ item.name }}" bond slaves '{{ item.members }}'
    atomic: true
  with_items: "{{ peerlink }}"
  when: peerlink is defined

- name: configure clag keepalive
  nclu:
    commands:
      - add interface peerlink.4094 ip address "{{ addresses[ansible_hostname].clag_ip }}"
      - add interface peerlink.4094 clag peer-ip "{{ addresses[ansible_hostname].clag_peer }}"
      - add interface peerlink.4094 clag sys-mac "{{ addresses[ansible_hostname].clag_mac }}"
    atomic: true

- name: Add source /etc/network/interfaces.d/*
  lineinfile: dest=/etc/network/interfaces state=present line='source /etc/network/interfaces.d/*' insertbefore=BOF
  become: yes

- name: Restart networking
  service: name=networking state=restarted
  become: yes
