---
- hosts: all
  user: vagrant
  become: yes
  tasks:
    - name: configure /etc/motd
      template: src=motd.j2 dest=/etc/motd

    - name: push hypervisors public SSH key
      authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
