---
- include: cleanup-for-ospf.yml

- include: leaf-setup.yml
  vars:
    v_file: "group_vars/all/main.yml"

- include: host-networking.yml
  vars:
    v_file: "group_vars/all/routing.yml"

- hosts: networking
  user: vagrant
  become: yes
  roles:
    - ebgp_unnum
  vars_files:
    - group_vars/all/routing.yml
  handlers:
    - include : handlers/main.yml
