---
- include: cleanup-for-clag.yml

- include: leaf-setup.yml
  vars:
    v_file: "group_vars/all/clag.yml"

- include: host-networking.yml
  vars:
    v_file: "group_vars/all/clag.yml"

- hosts: networking
  user: vagrant
  become: yes
  roles:
    - switch_clag
  vars_files:
    - group_vars/all/clag.yml
  handlers:
    - include : handlers/main.yml
